name 'puppet-zabbix-report'
version '0.0.1'
license 'Apache 2.0'
summary 'A Puppet report processor for sending metrics and failed runs to zabbix.'
project_page 'https://github.com/madAndroid/puppet-zabbix-report'
